//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.AMDC_API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AMDC_API.AMDCSoap")]
    public interface AMDCSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaTipoUsuarios", ReplyAction="*")]
        BACKEND.AMDC_API.consultaTipoUsuariosResponse consultaTipoUsuarios(BACKEND.AMDC_API.consultaTipoUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaTipoUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.consultaTipoUsuariosResponse> consultaTipoUsuariosAsync(BACKEND.AMDC_API.consultaTipoUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaUsuarios", ReplyAction="*")]
        BACKEND.AMDC_API.consultaUsuariosResponse consultaUsuarios(BACKEND.AMDC_API.consultaUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.consultaUsuariosResponse> consultaUsuariosAsync(BACKEND.AMDC_API.consultaUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento input del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToSHA256", ReplyAction="*")]
        BACKEND.AMDC_API.ConvertToSHA256Response ConvertToSHA256(BACKEND.AMDC_API.ConvertToSHA256Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToSHA256", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.ConvertToSHA256Response> ConvertToSHA256Async(BACKEND.AMDC_API.ConvertToSHA256Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento login del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarUsuario", ReplyAction="*")]
        BACKEND.AMDC_API.AgregarUsuarioResponse AgregarUsuario(BACKEND.AMDC_API.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.AgregarUsuarioResponse> AgregarUsuarioAsync(BACKEND.AMDC_API.AgregarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento login del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        BACKEND.AMDC_API.ActualizarUsuarioResponse ActualizarUsuario(BACKEND.AMDC_API.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.ActualizarUsuarioResponse> ActualizarUsuarioAsync(BACKEND.AMDC_API.ActualizarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        BACKEND.AMDC_API.EliminarUsuarioResponse EliminarUsuario(BACKEND.AMDC_API.EliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.EliminarUsuarioResponse> EliminarUsuarioAsync(BACKEND.AMDC_API.EliminarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validaLogin", ReplyAction="*")]
        BACKEND.AMDC_API.validaLoginResponse validaLogin(BACKEND.AMDC_API.validaLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validaLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.validaLoginResponse> validaLoginAsync(BACKEND.AMDC_API.validaLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaTipoUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaTipoUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.consultaTipoUsuariosRequestBody Body;
        
        public consultaTipoUsuariosRequest() {
        }
        
        public consultaTipoUsuariosRequest(BACKEND.AMDC_API.consultaTipoUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaTipoUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public consultaTipoUsuariosRequestBody() {
        }
        
        public consultaTipoUsuariosRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaTipoUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaTipoUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.consultaTipoUsuariosResponseBody Body;
        
        public consultaTipoUsuariosResponse() {
        }
        
        public consultaTipoUsuariosResponse(BACKEND.AMDC_API.consultaTipoUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaTipoUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultaTipoUsuariosResult;
        
        public consultaTipoUsuariosResponseBody() {
        }
        
        public consultaTipoUsuariosResponseBody(string consultaTipoUsuariosResult) {
            this.consultaTipoUsuariosResult = consultaTipoUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.consultaUsuariosRequestBody Body;
        
        public consultaUsuariosRequest() {
        }
        
        public consultaUsuariosRequest(BACKEND.AMDC_API.consultaUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public consultaUsuariosRequestBody() {
        }
        
        public consultaUsuariosRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.consultaUsuariosResponseBody Body;
        
        public consultaUsuariosResponse() {
        }
        
        public consultaUsuariosResponse(BACKEND.AMDC_API.consultaUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultaUsuariosResult;
        
        public consultaUsuariosResponseBody() {
        }
        
        public consultaUsuariosResponseBody(string consultaUsuariosResult) {
            this.consultaUsuariosResult = consultaUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToSHA256Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToSHA256", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.ConvertToSHA256RequestBody Body;
        
        public ConvertToSHA256Request() {
        }
        
        public ConvertToSHA256Request(BACKEND.AMDC_API.ConvertToSHA256RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToSHA256RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public ConvertToSHA256RequestBody() {
        }
        
        public ConvertToSHA256RequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToSHA256Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToSHA256Response", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.ConvertToSHA256ResponseBody Body;
        
        public ConvertToSHA256Response() {
        }
        
        public ConvertToSHA256Response(BACKEND.AMDC_API.ConvertToSHA256ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToSHA256ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToSHA256Result;
        
        public ConvertToSHA256ResponseBody() {
        }
        
        public ConvertToSHA256ResponseBody(string ConvertToSHA256Result) {
            this.ConvertToSHA256Result = ConvertToSHA256Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.AgregarUsuarioRequestBody Body;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(BACKEND.AMDC_API.AgregarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int usuacrea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string token;
        
        public AgregarUsuarioRequestBody() {
        }
        
        public AgregarUsuarioRequestBody(string login, string contrasenia, string nombre, int estado, int tipo, int usuacrea, string token) {
            this.login = login;
            this.contrasenia = contrasenia;
            this.nombre = nombre;
            this.estado = estado;
            this.tipo = tipo;
            this.usuacrea = usuacrea;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.AgregarUsuarioResponseBody Body;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(BACKEND.AMDC_API.AgregarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarUsuarioResult;
        
        public AgregarUsuarioResponseBody() {
        }
        
        public AgregarUsuarioResponseBody(string AgregarUsuarioResult) {
            this.AgregarUsuarioResult = AgregarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.ActualizarUsuarioRequestBody Body;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(BACKEND.AMDC_API.ActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string contrasenia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int estado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int usuacrea;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string token;
        
        public ActualizarUsuarioRequestBody() {
        }
        
        public ActualizarUsuarioRequestBody(int id, string login, string contrasenia, string nombre, int estado, int tipo, int usuacrea, string token) {
            this.id = id;
            this.login = login;
            this.contrasenia = contrasenia;
            this.nombre = nombre;
            this.estado = estado;
            this.tipo = tipo;
            this.usuacrea = usuacrea;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.ActualizarUsuarioResponseBody Body;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(BACKEND.AMDC_API.ActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarUsuarioResult;
        
        public ActualizarUsuarioResponseBody() {
        }
        
        public ActualizarUsuarioResponseBody(string ActualizarUsuarioResult) {
            this.ActualizarUsuarioResult = ActualizarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.EliminarUsuarioRequestBody Body;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(BACKEND.AMDC_API.EliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public EliminarUsuarioRequestBody() {
        }
        
        public EliminarUsuarioRequestBody(int id, string token) {
            this.id = id;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.EliminarUsuarioResponseBody Body;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(BACKEND.AMDC_API.EliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarUsuarioResult;
        
        public EliminarUsuarioResponseBody() {
        }
        
        public EliminarUsuarioResponseBody(string EliminarUsuarioResult) {
            this.EliminarUsuarioResult = EliminarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaLogin", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.validaLoginRequestBody Body;
        
        public validaLoginRequest() {
        }
        
        public validaLoginRequest(BACKEND.AMDC_API.validaLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validaLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validaLoginRequestBody() {
        }
        
        public validaLoginRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BACKEND.AMDC_API.validaLoginResponseBody Body;
        
        public validaLoginResponse() {
        }
        
        public validaLoginResponse(BACKEND.AMDC_API.validaLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validaLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validaLoginResult;
        
        public validaLoginResponseBody() {
        }
        
        public validaLoginResponseBody(string validaLoginResult) {
            this.validaLoginResult = validaLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AMDCSoapChannel : BACKEND.AMDC_API.AMDCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AMDCSoapClient : System.ServiceModel.ClientBase<BACKEND.AMDC_API.AMDCSoap>, BACKEND.AMDC_API.AMDCSoap {
        
        public AMDCSoapClient() {
        }
        
        public AMDCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AMDCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AMDCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AMDCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.consultaTipoUsuariosResponse BACKEND.AMDC_API.AMDCSoap.consultaTipoUsuarios(BACKEND.AMDC_API.consultaTipoUsuariosRequest request) {
            return base.Channel.consultaTipoUsuarios(request);
        }
        
        public string consultaTipoUsuarios(string token) {
            BACKEND.AMDC_API.consultaTipoUsuariosRequest inValue = new BACKEND.AMDC_API.consultaTipoUsuariosRequest();
            inValue.Body = new BACKEND.AMDC_API.consultaTipoUsuariosRequestBody();
            inValue.Body.token = token;
            BACKEND.AMDC_API.consultaTipoUsuariosResponse retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).consultaTipoUsuarios(inValue);
            return retVal.Body.consultaTipoUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.consultaTipoUsuariosResponse> BACKEND.AMDC_API.AMDCSoap.consultaTipoUsuariosAsync(BACKEND.AMDC_API.consultaTipoUsuariosRequest request) {
            return base.Channel.consultaTipoUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.consultaTipoUsuariosResponse> consultaTipoUsuariosAsync(string token) {
            BACKEND.AMDC_API.consultaTipoUsuariosRequest inValue = new BACKEND.AMDC_API.consultaTipoUsuariosRequest();
            inValue.Body = new BACKEND.AMDC_API.consultaTipoUsuariosRequestBody();
            inValue.Body.token = token;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).consultaTipoUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.consultaUsuariosResponse BACKEND.AMDC_API.AMDCSoap.consultaUsuarios(BACKEND.AMDC_API.consultaUsuariosRequest request) {
            return base.Channel.consultaUsuarios(request);
        }
        
        public string consultaUsuarios(string token) {
            BACKEND.AMDC_API.consultaUsuariosRequest inValue = new BACKEND.AMDC_API.consultaUsuariosRequest();
            inValue.Body = new BACKEND.AMDC_API.consultaUsuariosRequestBody();
            inValue.Body.token = token;
            BACKEND.AMDC_API.consultaUsuariosResponse retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).consultaUsuarios(inValue);
            return retVal.Body.consultaUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.consultaUsuariosResponse> BACKEND.AMDC_API.AMDCSoap.consultaUsuariosAsync(BACKEND.AMDC_API.consultaUsuariosRequest request) {
            return base.Channel.consultaUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.consultaUsuariosResponse> consultaUsuariosAsync(string token) {
            BACKEND.AMDC_API.consultaUsuariosRequest inValue = new BACKEND.AMDC_API.consultaUsuariosRequest();
            inValue.Body = new BACKEND.AMDC_API.consultaUsuariosRequestBody();
            inValue.Body.token = token;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).consultaUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.ConvertToSHA256Response BACKEND.AMDC_API.AMDCSoap.ConvertToSHA256(BACKEND.AMDC_API.ConvertToSHA256Request request) {
            return base.Channel.ConvertToSHA256(request);
        }
        
        public string ConvertToSHA256(string input) {
            BACKEND.AMDC_API.ConvertToSHA256Request inValue = new BACKEND.AMDC_API.ConvertToSHA256Request();
            inValue.Body = new BACKEND.AMDC_API.ConvertToSHA256RequestBody();
            inValue.Body.input = input;
            BACKEND.AMDC_API.ConvertToSHA256Response retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).ConvertToSHA256(inValue);
            return retVal.Body.ConvertToSHA256Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.ConvertToSHA256Response> BACKEND.AMDC_API.AMDCSoap.ConvertToSHA256Async(BACKEND.AMDC_API.ConvertToSHA256Request request) {
            return base.Channel.ConvertToSHA256Async(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.ConvertToSHA256Response> ConvertToSHA256Async(string input) {
            BACKEND.AMDC_API.ConvertToSHA256Request inValue = new BACKEND.AMDC_API.ConvertToSHA256Request();
            inValue.Body = new BACKEND.AMDC_API.ConvertToSHA256RequestBody();
            inValue.Body.input = input;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).ConvertToSHA256Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.AgregarUsuarioResponse BACKEND.AMDC_API.AMDCSoap.AgregarUsuario(BACKEND.AMDC_API.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public string AgregarUsuario(string login, string contrasenia, string nombre, int estado, int tipo, int usuacrea, string token) {
            BACKEND.AMDC_API.AgregarUsuarioRequest inValue = new BACKEND.AMDC_API.AgregarUsuarioRequest();
            inValue.Body = new BACKEND.AMDC_API.AgregarUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.nombre = nombre;
            inValue.Body.estado = estado;
            inValue.Body.tipo = tipo;
            inValue.Body.usuacrea = usuacrea;
            inValue.Body.token = token;
            BACKEND.AMDC_API.AgregarUsuarioResponse retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).AgregarUsuario(inValue);
            return retVal.Body.AgregarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.AgregarUsuarioResponse> BACKEND.AMDC_API.AMDCSoap.AgregarUsuarioAsync(BACKEND.AMDC_API.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.AgregarUsuarioResponse> AgregarUsuarioAsync(string login, string contrasenia, string nombre, int estado, int tipo, int usuacrea, string token) {
            BACKEND.AMDC_API.AgregarUsuarioRequest inValue = new BACKEND.AMDC_API.AgregarUsuarioRequest();
            inValue.Body = new BACKEND.AMDC_API.AgregarUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.nombre = nombre;
            inValue.Body.estado = estado;
            inValue.Body.tipo = tipo;
            inValue.Body.usuacrea = usuacrea;
            inValue.Body.token = token;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.ActualizarUsuarioResponse BACKEND.AMDC_API.AMDCSoap.ActualizarUsuario(BACKEND.AMDC_API.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public string ActualizarUsuario(int id, string login, string contrasenia, string nombre, int estado, int tipo, int usuacrea, string token) {
            BACKEND.AMDC_API.ActualizarUsuarioRequest inValue = new BACKEND.AMDC_API.ActualizarUsuarioRequest();
            inValue.Body = new BACKEND.AMDC_API.ActualizarUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.login = login;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.nombre = nombre;
            inValue.Body.estado = estado;
            inValue.Body.tipo = tipo;
            inValue.Body.usuacrea = usuacrea;
            inValue.Body.token = token;
            BACKEND.AMDC_API.ActualizarUsuarioResponse retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).ActualizarUsuario(inValue);
            return retVal.Body.ActualizarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.ActualizarUsuarioResponse> BACKEND.AMDC_API.AMDCSoap.ActualizarUsuarioAsync(BACKEND.AMDC_API.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.ActualizarUsuarioResponse> ActualizarUsuarioAsync(int id, string login, string contrasenia, string nombre, int estado, int tipo, int usuacrea, string token) {
            BACKEND.AMDC_API.ActualizarUsuarioRequest inValue = new BACKEND.AMDC_API.ActualizarUsuarioRequest();
            inValue.Body = new BACKEND.AMDC_API.ActualizarUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.login = login;
            inValue.Body.contrasenia = contrasenia;
            inValue.Body.nombre = nombre;
            inValue.Body.estado = estado;
            inValue.Body.tipo = tipo;
            inValue.Body.usuacrea = usuacrea;
            inValue.Body.token = token;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.EliminarUsuarioResponse BACKEND.AMDC_API.AMDCSoap.EliminarUsuario(BACKEND.AMDC_API.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public string EliminarUsuario(int id, string token) {
            BACKEND.AMDC_API.EliminarUsuarioRequest inValue = new BACKEND.AMDC_API.EliminarUsuarioRequest();
            inValue.Body = new BACKEND.AMDC_API.EliminarUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.token = token;
            BACKEND.AMDC_API.EliminarUsuarioResponse retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).EliminarUsuario(inValue);
            return retVal.Body.EliminarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.EliminarUsuarioResponse> BACKEND.AMDC_API.AMDCSoap.EliminarUsuarioAsync(BACKEND.AMDC_API.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.EliminarUsuarioResponse> EliminarUsuarioAsync(int id, string token) {
            BACKEND.AMDC_API.EliminarUsuarioRequest inValue = new BACKEND.AMDC_API.EliminarUsuarioRequest();
            inValue.Body = new BACKEND.AMDC_API.EliminarUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.token = token;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).EliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BACKEND.AMDC_API.validaLoginResponse BACKEND.AMDC_API.AMDCSoap.validaLogin(BACKEND.AMDC_API.validaLoginRequest request) {
            return base.Channel.validaLogin(request);
        }
        
        public string validaLogin(string usuario, string password) {
            BACKEND.AMDC_API.validaLoginRequest inValue = new BACKEND.AMDC_API.validaLoginRequest();
            inValue.Body = new BACKEND.AMDC_API.validaLoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            BACKEND.AMDC_API.validaLoginResponse retVal = ((BACKEND.AMDC_API.AMDCSoap)(this)).validaLogin(inValue);
            return retVal.Body.validaLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BACKEND.AMDC_API.validaLoginResponse> BACKEND.AMDC_API.AMDCSoap.validaLoginAsync(BACKEND.AMDC_API.validaLoginRequest request) {
            return base.Channel.validaLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BACKEND.AMDC_API.validaLoginResponse> validaLoginAsync(string usuario, string password) {
            BACKEND.AMDC_API.validaLoginRequest inValue = new BACKEND.AMDC_API.validaLoginRequest();
            inValue.Body = new BACKEND.AMDC_API.validaLoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((BACKEND.AMDC_API.AMDCSoap)(this)).validaLoginAsync(inValue);
        }
    }
}
