//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcaldia.AMDC_EMPRESAS_API {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AMDC_EMPRESAS_API.AMDC_EMPRESASSoap")]
    public interface AMDC_EMPRESASSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaDeclaracion", ReplyAction="*")]
        Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponse consultaDeclaracion(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaDeclaracion", ReplyAction="*")]
        System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponse> consultaDeclaracionAsync(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaDeclaracionesTotales", ReplyAction="*")]
        Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponse consultaDeclaracionesTotales(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaDeclaracionesTotales", ReplyAction="*")]
        System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponse> consultaDeclaracionesTotalesAsync(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento jsonParams del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaDeclaracionRenta", ReplyAction="*")]
        Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponse CalculaDeclaracionRenta(Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaDeclaracionRenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponse> CalculaDeclaracionRentaAsync(Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaDeclaracionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaDeclaracion", Namespace="http://tempuri.org/", Order=0)]
        public Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequestBody Body;
        
        public consultaDeclaracionRequest() {
        }
        
        public consultaDeclaracionRequest(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaDeclaracionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public consultaDeclaracionRequestBody() {
        }
        
        public consultaDeclaracionRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaDeclaracionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaDeclaracionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponseBody Body;
        
        public consultaDeclaracionResponse() {
        }
        
        public consultaDeclaracionResponse(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaDeclaracionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultaDeclaracionResult;
        
        public consultaDeclaracionResponseBody() {
        }
        
        public consultaDeclaracionResponseBody(string consultaDeclaracionResult) {
            this.consultaDeclaracionResult = consultaDeclaracionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaDeclaracionesTotalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaDeclaracionesTotales", Namespace="http://tempuri.org/", Order=0)]
        public Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequestBody Body;
        
        public consultaDeclaracionesTotalesRequest() {
        }
        
        public consultaDeclaracionesTotalesRequest(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaDeclaracionesTotalesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public consultaDeclaracionesTotalesRequestBody() {
        }
        
        public consultaDeclaracionesTotalesRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaDeclaracionesTotalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaDeclaracionesTotalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponseBody Body;
        
        public consultaDeclaracionesTotalesResponse() {
        }
        
        public consultaDeclaracionesTotalesResponse(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaDeclaracionesTotalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultaDeclaracionesTotalesResult;
        
        public consultaDeclaracionesTotalesResponseBody() {
        }
        
        public consultaDeclaracionesTotalesResponseBody(string consultaDeclaracionesTotalesResult) {
            this.consultaDeclaracionesTotalesResult = consultaDeclaracionesTotalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaDeclaracionRentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaDeclaracionRenta", Namespace="http://tempuri.org/", Order=0)]
        public Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequestBody Body;
        
        public CalculaDeclaracionRentaRequest() {
        }
        
        public CalculaDeclaracionRentaRequest(Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculaDeclaracionRentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonParams;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public CalculaDeclaracionRentaRequestBody() {
        }
        
        public CalculaDeclaracionRentaRequestBody(string jsonParams, string token) {
            this.jsonParams = jsonParams;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaDeclaracionRentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaDeclaracionRentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponseBody Body;
        
        public CalculaDeclaracionRentaResponse() {
        }
        
        public CalculaDeclaracionRentaResponse(Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculaDeclaracionRentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculaDeclaracionRentaResult;
        
        public CalculaDeclaracionRentaResponseBody() {
        }
        
        public CalculaDeclaracionRentaResponseBody(string CalculaDeclaracionRentaResult) {
            this.CalculaDeclaracionRentaResult = CalculaDeclaracionRentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AMDC_EMPRESASSoapChannel : Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AMDC_EMPRESASSoapClient : System.ServiceModel.ClientBase<Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap>, Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap {
        
        public AMDC_EMPRESASSoapClient() {
        }
        
        public AMDC_EMPRESASSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AMDC_EMPRESASSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AMDC_EMPRESASSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AMDC_EMPRESASSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponse Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap.consultaDeclaracion(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest request) {
            return base.Channel.consultaDeclaracion(request);
        }
        
        public string consultaDeclaracion(string token) {
            Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest inValue = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest();
            inValue.Body = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequestBody();
            inValue.Body.token = token;
            Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponse retVal = ((Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap)(this)).consultaDeclaracion(inValue);
            return retVal.Body.consultaDeclaracionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponse> Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap.consultaDeclaracionAsync(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest request) {
            return base.Channel.consultaDeclaracionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionResponse> consultaDeclaracionAsync(string token) {
            Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest inValue = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequest();
            inValue.Body = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionRequestBody();
            inValue.Body.token = token;
            return ((Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap)(this)).consultaDeclaracionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponse Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap.consultaDeclaracionesTotales(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest request) {
            return base.Channel.consultaDeclaracionesTotales(request);
        }
        
        public string consultaDeclaracionesTotales(string token) {
            Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest inValue = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest();
            inValue.Body = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequestBody();
            inValue.Body.token = token;
            Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponse retVal = ((Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap)(this)).consultaDeclaracionesTotales(inValue);
            return retVal.Body.consultaDeclaracionesTotalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponse> Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap.consultaDeclaracionesTotalesAsync(Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest request) {
            return base.Channel.consultaDeclaracionesTotalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesResponse> consultaDeclaracionesTotalesAsync(string token) {
            Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest inValue = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequest();
            inValue.Body = new Alcaldia.AMDC_EMPRESAS_API.consultaDeclaracionesTotalesRequestBody();
            inValue.Body.token = token;
            return ((Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap)(this)).consultaDeclaracionesTotalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponse Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap.CalculaDeclaracionRenta(Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest request) {
            return base.Channel.CalculaDeclaracionRenta(request);
        }
        
        public string CalculaDeclaracionRenta(string jsonParams, string token) {
            Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest inValue = new Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest();
            inValue.Body = new Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequestBody();
            inValue.Body.jsonParams = jsonParams;
            inValue.Body.token = token;
            Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponse retVal = ((Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap)(this)).CalculaDeclaracionRenta(inValue);
            return retVal.Body.CalculaDeclaracionRentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponse> Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap.CalculaDeclaracionRentaAsync(Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest request) {
            return base.Channel.CalculaDeclaracionRentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaResponse> CalculaDeclaracionRentaAsync(string jsonParams, string token) {
            Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest inValue = new Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequest();
            inValue.Body = new Alcaldia.AMDC_EMPRESAS_API.CalculaDeclaracionRentaRequestBody();
            inValue.Body.jsonParams = jsonParams;
            inValue.Body.token = token;
            return ((Alcaldia.AMDC_EMPRESAS_API.AMDC_EMPRESASSoap)(this)).CalculaDeclaracionRentaAsync(inValue);
        }
    }
}
